# Generated by Django 5.2.5 on 2025-09-06 16:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счёт"),
                    ("stripe", "Stripe"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
