# Generated by Django 5.2.5 on 2025-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_checkout_url_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
