# Generated by Django 5.2.5 on 2025-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
